
namespace App1 {

[default_interface] runtimeclass MainWindow : Microsoft.UI.Xaml.Window {
    MainWindow();

    Windows.System.DispatcherQueue BackgroundQueue;

    Windows.Foundation.IAsyncAction ChangeTheme();
}
} // namespace App1
